## Numpy array and basics

In [1]:
import numpy as np 

### Creating array from list

In [2]:
array_1d = np.array([1,2,3,4,5])
print("1D array : ",array_1d)

array_2d = np.array([[1,2,3],[4,5,6]])
print("2D array : ",array_2d)   

1D array :  [1 2 3 4 5]
2D array :  [[1 2 3]
 [4 5 6]]


### List vs Numpy array

In [3]:
py_list = [1,2,3]
print("Python list multiplication : ",py_list * 2)


np_array = np.array([1,2,3])  # Element wise multiplication  
print("Python array multiplication : ",np_array * 2)


import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\nList operation time : ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\nArray operation time : ", time.time() - start)

Python list multiplication :  [1, 2, 3, 1, 2, 3]
Python array multiplication :  [2 4 6]

List operation time :  0.1544952392578125

Array operation time :  0.008402347564697266


### Creating array from scratch

In [4]:
# Array of Zeros
zeros = np.zeros((3,4))
print("Zeros Array : \n",zeros,"\n")

# Array of ones
ones = np.ones((2,3))
print("Ones Array : \n",ones,"\n")

# Array of a particular number 
full = np.full((2,2),7)
print("Full Array : \n",full,"\n")

# Random Array
random = np.random.random((2,3))
print("Random Array : \n",random,"\n") 

Zeros Array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

Ones Array : 
 [[1. 1. 1.]
 [1. 1. 1.]] 

Full Array : 
 [[7 7]
 [7 7]] 

Random Array : 
 [[0.34461397 0.27519619 0.58639153]
 [0.83874925 0.10372563 0.60781742]] 



### Vector , Matrix and Tensor

In [5]:
vector = np.array([1,2,3])
print("Vector : ",vector)


matrix = np.array([[1,2,3],
                   [4,5,6]])
print("Matrix : ",matrix)


tensor = np.array([[[1,2,3],[4,5,6]],
                   [[7,8,9],[10,11,12]]])
print("Tensor : ",tensor)

Vector :  [1 2 3]
Matrix :  [[1 2 3]
 [4 5 6]]
Tensor :  [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### Array Properties

In [6]:
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print("Shape : ",arr.shape)
print("Dimensions : ",arr.ndim)
print("Size : ",arr.size)
print("Data Type : ",arr.dtype)

Shape :  (3, 3)
Dimensions :  2
Size :  9
Data Type :  int64


### Array Reshaping

In [7]:
arr = np.arange(12)
print("Original Array : ",arr)

# Reshaping the array
reshaped = arr.reshape((3,4))
print("\nReshaped Array : ",reshaped)

# To flatten the array again
flattened = reshaped.flatten()
print("\nFlattened Array : ",flattened)

# ravel() - It returns view instead of copy
raveled = reshaped.ravel()
print("\nRaveled Array : ",raveled)

# Transpose
transposed = reshaped.T
print("\nTransposed Array : ",transposed)


Original Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped Array :  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Raveled Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Transposed Array :  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
