# Numpy Array operations

In [1]:
import numpy as np

### Slicing in 1d array


In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print("Basic Slicing :",arr[2:7])
print("Step Slicing : ",arr[1:8])
print("Negative Slicing : ",arr[-3])

Basic Slicing : [3 4 5 6 7]
Step Slicing :  [2 3 4 5 6 7 8]
Negative Slicing :  8


### Slicing in 2d array


In [3]:
arr_2d = np.array([[1,2,3],
           [4,5,6],
           [7,8,9]])

print("Specific Element : ",arr_2d[1,2])  # 1st row 2nd column 
print("Specific row : ",arr_2d[2])   # Prints specific row
print("Specific column : ",arr_2d[:,1])  # If you want only column use ":" instead of row number

Specific Element :  6
Specific row :  [7 8 9]
Specific column :  [2 5 8]


### Sorting



In [4]:
unsorted_arr = np.array([3,4,7,8,4,1,2,1,9])
print("Sorted array : ",np.sort(unsorted_arr))

unsorted_arr_2d = np.array([[3,1],[2,3],[1,2]])
print("Sorted 2d array : ",np.sort(unsorted_arr_2d,axis=0))  # Sorting top to bottom

print("Sorted 2d array : ",np.sort(unsorted_arr_2d,axis=1))  # Sorting left to right


Sorted array :  [1 1 2 3 4 4 7 8 9]
Sorted 2d array :  [[1 1]
 [2 2]
 [3 3]]
Sorted 2d array :  [[1 3]
 [2 3]
 [1 2]]


## Filter


In [5]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers % 2 == 0]
print("Numbers divisible by 2 : ",even_numbers)

Numbers divisible by 2 :  [ 2  4  6  8 10]


### Filter with mask


In [6]:
mask = numbers > 5
print("Numbers greater than 5 : ",numbers[mask])

Numbers greater than 5 :  [ 6  7  8  9 10]


## Fancy indexing v/s np.where()

In [7]:
indices = [0,2,4]
print("Specific elements : ",numbers[indices])  # Prints specific elements

where_indices = np.where(numbers > 5)
print("Indices of numbers greater than 5 : ",numbers[where_indices])  # Prints indices of numbers greater than 5

Specific elements :  [1 3 5]
Indices of numbers greater than 5 :  [ 6  7  8  9 10]


In [8]:
condition_array = np.where(numbers > 5, numbers*2,numbers)
print("Condition array : ",condition_array)  # Prints numbers greater than 5 multiplied by 2, else prints the number itself

Condition array :  [ 1  2  3  4  5 12 14 16 18 20]


## Adding and removing array


In [9]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

combined_arr = np.concatenate((arr1, arr2))
print("Combined array : ",combined_arr)  # Prints combined array

Combined array :  [ 1  2  3  4  5  6  7  8  9 10]


### Array Compatibility


In [10]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("Compatibility shapes check : ", a.shape == b.shape)  # Checks if all elements are equal

Compatibility shapes check :  True


### Adding rows and columns

In [11]:
original_arr = np.array([[1,2,3],[4,5,6]])
new_row = np.array([7,8,9])

arr_with_new_row = np.vstack([original_arr, new_row])
print("Array after adding new row : ",arr_with_new_row)  # Prints array after adding new row

new_column = np.array([[10],[11]])


with_new_column = np.hstack([original_arr, new_column])
print("Array after adding new column : ",with_new_column)  # Prints array after adding new column

Array after adding new row :  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array after adding new column :  [[ 1  2  3 10]
 [ 4  5  6 11]]


### Delete Array


In [12]:
original_arr = np.array([1,2,3,4,5])
deleted_arr = np.delete(original_arr, 2)  # Deletes the element at index 2

print("Array after deleting element at index 2 : ",deleted_arr)  # Prints array after deleting element at index 2

Array after deleting element at index 2 :  [1 2 4 5]
